### ISSUE TITLE
Option to limit icon amount

### ISSUE THREAD

**Issue by Averyfrog** [hyprland-community/hyprland-autoname-workspaces#105]
**Problem**
When the workspace is displaying too many icons, it extends the width of my bar (i use a vertical EWW bar)

**Solution**
an option to only display the first *x* amount icons

**Comment by cyrinux** [comment]
Hi, can you try this branch? https://github.com/hyprland-community/hyprland-autoname-workspaces/tree/feat/max-clients-params

**Comment by Averyfrog** [comment]
I installed it with the branch and added `max_clients = 2` to my config, but it doesn't seem to limit the icon amount.

It is possible i installed it wrong since I'm still relatively new to arch, so if it's any help here is how i installed it:
I installed the package by cloning the repository
`git clone https://github.com/hyprland-community/hyprland-autoname-workspaces -b feat/max-clients-params`
and then ran
`cargo install --locked hyprland-autoname-workspaces`
i ran the file using 
`/.cargo/bin/./hyprland-autoname-workspaces`
and it ran as normal, icons still exceeding 2

if you need any other info or to test anything else i'm happy to try and help!

**Comment by cyrinux** [comment]
Just run `cargo run` from the repo you clone, with the good branch.

**Comment by Averyfrog** [comment]
this works perfectly!
thanks for adding this :)

**Comment by cyrinux** [comment]
its release https://github.com/hyprland-community/hyprland-autoname-workspaces/releases/tag/1.1.12
