### ISSUE TITLE
[BUG] hyprland-autoname-workspace broken since hyprland moved SOCK location

### ISSUE THREAD

**Issue by fiskhest** [hyprland-community/hyprland-autoname-workspaces#110]
**Describe the bug**
hyprland-autoname-workspace cannot run under hyprland v0.40.0 since hyprland [moved the location of its socket](https://github.com/hyprwm/Hyprland/releases/tag/v0.40.0).

**Program version?**

❯ hyprland-autoname-workspaces --version        
hyprland-autoname-workspaces 1.1.13

**To Reproduce**

1. Install latest hyprland-autoname-workspace
2. Run `hyprland-autoname-workspace`
```
❯ hyprland-autoname-workspaces
thread 'main' panicked at /home/johan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyprland-0.3.13/src/data/regular.rs:31:19:
A error occured while parsing the output from the hypr socket: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
hyprland-autoname-workspaces runs cleanly

**Linux Distro (please complete the following information):**

- Arch Linux

**Additional context**
I believe this issue comes from using an older version of `hyprland-rs`. It seems `hyprswitch` [successfully bumped it's dependencies](https://github.com/H3rmt/hyprswitch/blob/28efc3d342f0466b5201d2336a0658711c4d282d/Cargo.toml#L16) and use the new alpha version. My rust skills are worthless at best, so I cannot verify and PR this on my own.

**Comment by noggynoggy** [comment]
Can confirm issue on NixOS using the official Hyprland flake.

**Comment by noggynoggy** [comment]
Can we get this as release? The [nixpackage](https://github.com/NixOS/nixpkgs/blob/2230a20f2b5a14f2db3d7f13a2dc3c22517e790b/pkgs/applications/misc/hyprland-autoname-workspaces/default.nix#L8) just defines a version. Otherwise, someone (?) would have to maybe make a flake.

**Comment by cyrinux** [comment]
done!
