### ISSUE TITLE
[BUG] thread 'main' panicked at src/renamer/mod.rs:278:34:

### ISSUE THREAD

**Issue by akohlen** [hyprland-community/hyprland-autoname-workspaces#113]
**Describe the bug**
thread 'main' panicked at src/renamer/mod.rs:278:34:
called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid type: integer `0`, expected a boolean", line: 21, column: 19))

(after updating from 1.1.13 to 1.1.14 and updating the config.toml)

**Program version?**
hyprland-autoname-workspaces 1.1.14
from AUR hyprland-autoname-workspaces-git 1.1.14.r0.gf514385-1

**Program configuration dump? (ideally)**
```
{
  "version": "1.1.14",
  "class": {
    "org.kde.kcalc": "<span color=\"#FFFFFF\"></span>",
    "google-chrome": "<span color=\"#FFFFFF\"></span>"
  },
  "class_active": {
    "DEFAULT": "*{icon}*",
    "(?i)ExampleOneTerm": "<span foreground='red'>{icon}</span>"
  },
  "initial_class": {},
  "initial_class_active": {},
  "workspaces_name": {
    "10": "ten",
    "5": "five",
    "7": "seven",
    "3": "three",
    "4": "four",
    "6": "six",
    "1": "one",
    "9": "nine",
    "2": "two",
    "8": "eight"
  },
  "title_in_class": {
    "(?i)kitty": {
      "(?i)neomutt": "neomutt"
    }
  },
  "title_in_class_active": {
    "(?i)firefox": {
      "(?i)twitch": "<span color='purple'>{icon}</span>"
    }
  },
  "title_in_initial_class": {},
  "title_in_initial_class_active": {},
  "initial_title_in_class": {},
  "initial_title_in_class_active": {},
  "initial_title_in_initial_class": {},
  "initial_title_in_initial_class_active": {},
  "exclude": {
    "": "^$",
    "[Ss]team": "^(Friends List.*)?$",
    "(?i)TestApp": "",
    "(?i)fcitx": ".*",
    "aProgram": "^$"
  },
  "format": {
    "max_clients": 99,
    "dedup": false,
    "dedup_inactive_fullscreen": false,
    "delim": " ",
    "workspace": "{id}:{delim}{clients}",
    "workspace_empty": "{id}",
    "client": "{icon}",
    "client_fullscreen": "[{icon}]",
    "client_active": "*{icon}*",
    "client_dup": "{icon}{counter_sup}",
    "client_dup_active": "*{icon}*{delim}{icon}{counter_unfocused_sup}",
    "client_dup_fullscreen": "[{icon}]{delim}{icon}{counter_unfocused_sup}"
  }
}

```

**To Reproduce**
1. call hyprland-autoname-workspaces

`thread 'main' panicked at src/renamer/mod.rs:278:34:
called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid type: integer `0`, expected a boolean", line: 21, column: 19))

`stack backtrace:
   0:     0x64dfe8118ec5 - <unknown>
   1:     0x64dfe813cfdb - <unknown>
   2:     0x64dfe81163df - <unknown>
   3:     0x64dfe8118c9e - <unknown>
   4:     0x64dfe811a039 - <unknown>
   5:     0x64dfe8119dda - <unknown>
   6:     0x64dfe811a4d3 - <unknown>
   7:     0x64dfe811a3b4 - <unknown>
   8:     0x64dfe8119389 - <unknown>
   9:     0x64dfe811a0e7 - <unknown>
  10:     0x64dfe7f27193 - <unknown>
  11:     0x64dfe7f27626 - <unknown>
  12:     0x64dfe7f365bc - <unknown>
  13:     0x64dfe7f6d458 - <unknown>
  14:     0x64dfe7f6ee83 - <unknown>
  15:     0x64dfe7f660f9 - <unknown>
  16:     0x64dfe8110dcd - <unknown>
  17:     0x64dfe7f6e4d5 - <unknown>
  18:     0x73268cec9e08 - <unknown>
  19:     0x73268cec9ecc - __libc_start_main
  20:     0x64dfe7f27925 - <unknown>
  21:                0x0 - <unknown>`

**Expected behavior**
no panicking

**Linux Distro (please complete the following information):**
6.10.2-arch1-2 with hyprland-git 0.41.2.r165.2b520571-1

**Comment by tom-gora** [comment]
Confirming same behavior on Fedora Server 40

**Comment by FieldofClay** [comment]
Issue is upstream in hyprland-rs: https://github.com/hyprland-community/hyprland-rs/issues/262

**Comment by mentalAdventurer** [comment]
Is there a workaround in the meantime?

**Comment by cyrinux** [comment]
Hello, I got something working on the main branch but I have to clean it a little and we need to do a release of hyprland-rs first to be able to release too.

**Comment by cyrinux** [comment]
I release a tag for the hyprland-rs v4 alpha and create a new release. 
https://github.com/hyprland-community/hyprland-autoname-workspaces/releases/tag/1.1.15
