### ISSUE TITLE
make the active window's icon a different colour

### ISSUE THREAD

**Issue by ehula** [hyprland-community/hyprland-autoname-workspaces#46]
Is it possible to introduce styling of workspace icons?

I would love to be able to give the icon of the active window a different colour so that it stands out among the other windows. This would also have the benefit of being able to remove the square brackets currently being used.

Is this possible? Would it conflict with waybar's styling?

**Comment by cyrinux** [comment]
Good question, in the futur version the span color will work, after, if we want to enable the color ONLY for the active workspace there is more work I think or trick to find.
I will think about it.

**Comment by ehula** [comment]
Just to clarify, I'd like to use span color for the active "window" on a workspace, not for the active "workspace". I think maybe you just mis-typed "workspace".

As an example, if I have three windows open on the current workspace, I would like to span color just the icon of the active window.

**Comment by cyrinux** [comment]
I'm tired and missread but I will to think about this and try things. I will keep you in touch when this topic move. 👍

**Comment by psimovec** [comment]
> Is it possible to introduce styling of workspace icons?
> 
> I would love to be able to give the icon of the active window a different colour so that it stands out among the other windows. This would also have the benefit of being able to remove the square brackets currently being used.
> 
> Is this possible? Would it conflict with waybar's styling?

Good idea, I think it should be doable.
In my opinion, it could be taken from code and made accessible in config in style like
defaults:

```
delim=" "
workspace="{id}: {clients}"
client="{client}" # generic app/client
active_client="{client}" #priority over app
dup_client="{client}{s_count}" #s_count - superscripted count of clients on the workspace, but {count} should be available too
```

so you could modify it as you wish, for example:
```
delim=" " # NARROW NO-BREAK SPACE
workspace="<span whatever="options" ...>{id}</span>{clients}" # https://docs.gtk.org/Pango/pango_markup.html
client="<span color='grey'>{client}</span>" # generic client
active_client="<span color='white'>{client}</span>" #priority over generic client
dup_client="{client}<span color='red'>{s_count}</span>" 
```

I just made a {WIP] PR for generalizing delimiter https://github.com/cyrinux/hyprland-autoname-workspaces/pull/47, other things could be implemented similarly.

**Comment by cyrinux** [comment]
Very good design to be adopt for the future yes. We will add a `[format] ` config section for this and try to reach this.

**Comment by cyrinux** [comment]
I start implementing this.

**Comment by cyrinux** [comment]
FYI, I reach a step where I can have formatter working BUT not yet active window formatter. It needs a more bigger refactor and studies as we need to go in async mode now for this.

**Comment by cyrinux** [comment]
@ehula @psimovec @maximbaz  can you try the following PR please ?  https://github.com/hyprland-community/hyprland-autoname-workspaces/pull/49 
 
The formatters are available - but WIP.  The one for the active window is not yet available. More refactoring of the code is needed but I should come then.

You can `git checkout feat/add-formatters` then `cargo run` and check the README and `config.toml.example` for new formatters. 
 
Don't hestate to ask me questions. I will be happy to read you 🙏🏻

**Comment by cyrinux** [comment]
Batch 1 of the formatter is merge in master. I will try to refactor in async now to support the `active` events.

**Comment by cyrinux** [comment]
You can try this PR if you want https://github.com/hyprland-community/hyprland-autoname-workspaces/pull/50

**Comment by psimovec** [comment]
Nice update, I can adjust the workspaces quite well now, I am playing with the settings 
![image](https://github.com/hyprland-community/hyprland-autoname-workspaces/assets/52415835/e424d0ee-b7b9-4fe3-acf7-12f58a85fdb0)

Just some details I found:
 I am trying on master for now, the delimiter got broken. On my PR afaik it was always between clients (before 2nd+ client on each workspace), now it is before or after _every_ screen.
![image](https://github.com/hyprland-community/hyprland-autoname-workspaces/assets/52415835/c564a7cb-68b7-46c9-bc16-4bd7ca55335c)

Another issue I found.. I guess the biggest problem is I can't properly sort by id in the wlr/workspaces module of waybar, so there is the sort by name..
And I saw in code, that if there is no client on workspace, the workspace does not get renamed at all, which breaks the sort (as otherwhise there would be some `<span...` on start in my case
![image](https://github.com/hyprland-community/hyprland-autoname-workspaces/assets/52415835/c21bbc51-1a6a-4783-a4db-3003fce05041)

**Comment by cyrinux** [comment]
> Nice update, I can adjust the workspaces quite well now, I am playing with the settings ![image](https://user-images.githubusercontent.com/52415835/237236082-e424d0ee-b7b9-4fe3-acf7-12f58a85fdb0.png)
> 
> Just some details I found: I am trying on master for now, the delimiter got broken. On my PR afaik it was always between clients (before 2nd+ client on each workspace), now it is before or after _every_ screen. ![image](https://user-images.githubusercontent.com/52415835/237215878-c564a7cb-68b7-46c9-bc16-4bd7ca55335c.png)
> 
> Another issue I found.. I guess the biggest problem is I can't properly sort by id in the wlr/workspaces module of waybar, so there is the sort by name.. And I saw in code, that if there is no client on workspace, the workspace does not get renamed at all, which breaks the sort (as otherwhise there would be some `<span...` on start in my case ![image](https://user-images.githubusercontent.com/52415835/237234578-c21bbc51-1a6a-4783-a4db-3003fce05041.png) ![image](https://user-images.githubusercontent.com/52415835/237237982-05b5751b-597f-464f-8033-6a9b31e8f808.png)

Thanks for the tests @psimovec I will try to fix the bug if I well understand them. Will tell you if I need more informations.

**Comment by cyrinux** [comment]
I push some fixes try on #50 that also include active window detection

**Comment by psimovec** [comment]
> > Nice update, I can adjust the workspaces quite well now, I am playing with the settings ![image](https://user-images.githubusercontent.com/52415835/237236082-e424d0ee-b7b9-4fe3-acf7-12f58a85fdb0.png)
> > Just some details I found: I am trying on master for now, the delimiter got broken. On my PR afaik it was always between clients (before 2nd+ client on each workspace), now it is before or after _every_ screen. ![image](https://user-images.githubusercontent.com/52415835/237215878-c564a7cb-68b7-46c9-bc16-4bd7ca55335c.png)
> > Another issue I found.. I guess the biggest problem is I can't properly sort by id in the wlr/workspaces module of waybar, so there is the sort by name.. And I saw in code, that if there is no client on workspace, the workspace does not get renamed at all, which breaks the sort (as otherwhise there would be some `<span...` on start in my case ![image](https://user-images.githubusercontent.com/52415835/237234578-c21bbc51-1a6a-4783-a4db-3003fce05041.png) ![image](https://user-images.githubusercontent.com/52415835/237237982-05b5751b-597f-464f-8033-6a9b31e8f808.png)
> 
> Thanks for the tests @psimovec I will try to fix the bug if I well understand them. Can you share me the formatters you use to trigger the bug? Is it present with the default one? Will tell you if I need more informations.

```
delim=" " # NARROW NO-BREAK SPACE
client = "{icon}{delim}"
workspace="<span letter_spacing='-9000'> </span><span font_size='70%' rise='4pt' color='#D{id}D{id}FF'>{id} </span>{clients}<span letter_spacing='-18000'> </span>"
client_dup = "{icon}<span color='white' letter_spacing='000' font_size='100%' weight='1000' rise='-1pt'  >x{counter} </span>"
```

And here you can see relevant workspace names:
```
workspace ID 2 (<span letter_spacing='-9000'> </span><span font_size='70%' rise='4pt' color='#D2D2FF'>2 </span><span color="orange"> </span> <span letter_spacing='-18000'> </span>) on monitor eDP-1:
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x560460063540
	lastwindowtitle: Messenger — Mozilla Firefox


workspace ID 3 (<span letter_spacing='-9000'> </span><span font_size='70%' rise='4pt' color='#D3D3FF'>3 </span> <span color ="#6DBA49" ></span> <span letter_spacing='-18000'> </span>) on monitor eDP-1:
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x56045f9135f0
	lastwindowtitle: Signal

workspace ID 1 (1) on monitor eDP-1:
	windows: 0
	hasfullscreen: 0
	lastwindow: 0x0
	lastwindowtitle: 

```
The bug triggers when you have a workspace without any clients open.

With default one I suppose the bug doesn't happen, as by default workspaces are named `{id}: ...` so if the workspace is not renamed, it's name is just `{id}` for me, so it doesn't affect the ordering.

**Comment by cyrinux** [comment]
Thanks @psimovec , you learn me btw some span tricks.

The empty workspace bug is fix in theory, I introduce a new `workspace_empty` formatter equal to `{id}` by default. Also I rename and pass to the formatters even the workspace with no clients.

Also, about the bad ordering, @maximbaz just add some information in the FAQ https://github.com/hyprland-community/hyprland-autoname-workspaces/wiki/FAQ.

**Comment by cyrinux** [comment]
https://github.com/hyprland-community/hyprland-autoname-workspaces/releases/tag/0.5.1 (and 0.5.2) out \o/
