### ISSUE TITLE
Unable to switch workspaces by clicking on them

### ISSUE THREAD

**Issue by DaniAndTheWeb** [hyprland-community/hyprland-autoname-workspaces#51]
I'm on the latest git and when I tried to use the new format configuration on the workspaces I noticed that by applying it I've lost the ability to switch workspaces by clicking on the icon. Is this expected? If it is, is there a configuration parameter that it's not on the example and should be needed?

EDIT: The problem seems to disappear once I delete all the span configuration

**Comment by cyrinux** [comment]
Hi @DaniAndTheWeb, I will add a FAQ entry with the patch you need to use for waybar while its not in upstream nor in AUR or nix package.

You have to use this patch https://aur.archlinux.org/packages/waybar-hyprland-git#comment-912717

I wish we can have help to get this put in the nix and AUR package.

**Comment by DaniAndTheWeb** [comment]
Thanks for the fast response, I didn't think that it was related to the other close issue.
