### ISSUE TITLE
[BUG] workspace_empty

### ISSUE THREAD

**Issue by ehula** [hyprland-community/hyprland-autoname-workspaces#53]
**Describe the bug**
No matter what I set `workspace_empty` to, it always just displays `{id}`.

**To Reproduce**
1. Set `workspace_empty` to "empty".
2. Save the config file.
3. Restart waybar.
4. Open empty workspace.
5. Workspace is named `{id}`.

**Expected behavior**
Workspace should be named "empty".

**Linux Distro (please complete the following information):**
NixOS

**Program version?
0.5.2

**Comment by cyrinux** [comment]
Thanks we maybe have a bug yes, do you confirm you well have the style apply when your close ALL the app on a workspace and stay on this workspace ?

**Comment by ehula** [comment]
Ah. If I close all windows on a workspace, then the empty workspace is formatted correctly. But if I switch to an empty workspace that has not had any windows opened on it, it is not formatted correctly.

**Comment by cyrinux** [comment]
Hey hey, @ehula can you try the last release 0.5.3 ?

**Comment by ehula** [comment]
Looks like it is fixed.
