### ISSUE TITLE
[BUG] active window formatting is applied to ALL matching windows

### ISSUE THREAD

**Issue by ehula** [hyprland-community/hyprland-autoname-workspaces#54]
**Describe the bug**
When using `client_active` formatting, Instead of just formatting the active window in the current workspace, all windows in all workspaces that have the same class are formatted.
 
**To Reproduce**
1. Configure `client_active`
2. Open two `librewolf` instances on current workspace.
3. Go to another workspace.
4. Open another `librewofl` instance.
5. All `librewolf` icons will be formatted as active on both workspaces.

**Expected behavior**
Only one icon should be highlighted, the icon of the active window in the current workspace.

**Linux Distro (please complete the following information):**
NixOS

**Program version?
0.5.2

**Additional context**
Interestingly, this feature works properly for multiple instances of `kitty`.

**Comment by cyrinux** [comment]
Thanks for the report 😄 I'm happy to have some testers 👍🏻 I will be the next week less active on the project but I will fix this asap 😉

**Comment by cyrinux** [comment]
Fix in 0.5.4, we use `pid` as selector before for active window, but we need to use `address` to prevent app keeping the same pid when several instance open to trigger the bad behavior you have. 
Thanks for the report.
