### ISSUE TITLE
[BUG] client_active always adds one {delim}

### ISSUE THREAD

**Issue by ehula** [hyprland-community/hyprland-autoname-workspaces#55]
**Describe the bug**
If I use this example:
```
client = "{icon}{delim}"
client_active = "<span color="red">{icon}</span>{delim}"
```
there will be two {delim} after the active window.

**To Reproduce**
1. Configure as in the example above.
2. Open multiple windows on the current workspace.
3. Note that the active window has two {delim} after the {icon}.
4. Change active windows.
5. Note that the previously active window now only has one {delim} and the new active window now has two {delim}.

**Expected behavior**
The active window should get its formatting from `client_active`.

**Linux Distro (please complete the following information):**
NixOS

**Program version?
0.5.2

**Comment by cyrinux** [comment]
I feel like this should be fix when I will success to refactor it and join client by `{delim}` instead append this to each other. There is WIP about this. Thanks for the report.

**Comment by cyrinux** [comment]
Fixed in our refacto, to be release soon.

**Comment by cyrinux** [comment]
Should be fix in the new release https://github.com/hyprland-community/hyprland-autoname-workspaces/releases/tag/1.0.0
