### ISSUE TITLE
[BUG]AUR PKGBUILD miss  package name

### ISSUE THREAD

**Issue by 1m-N00b** [hyprland-community/hyprland-autoname-workspaces#56]
I can't update (git clone) to work in AUR.
I have looked at the PKGBUILD and can't figure out.

**Comment by cyrinux** [comment]
Hi @1m-N00b , can you give me more detail please? The command output of your errors please.

**Comment by maximbaz** [comment]
Hey, I think I know what error you are getting, because this project was moved into org, aurutils says that your cached git repo doesn't match this repo anymore, the solution is to nuke subfolders in ~/.cache/aurutils/sync/hyprland-autoname-workspaces-git/

**Comment by 1m-N00b** [comment]
I totally made that mistake...
I didn't realize it had moved.

**Comment by cyrinux** [comment]
It's my fault 😝
