### ISSUE TITLE
match `initialTitle`

### ISSUE THREAD

**Issue by ehula** [hyprland-community/hyprland-autoname-workspaces#57]
Can we match on `initialTitle`?

I have noticed that some windows' titles change over time. For instance, when I load my Jellyfin instance in my browser, the `initialTitle` contains the URL, but once I begin playing content, the title changes. It would be nice to instead have the option to match to the `initialTitle`.

**Comment by cyrinux** [comment]
Hi, I will check this after I finish my big refactoring. I see your point, I will check this. 👌

**Comment by cyrinux** [comment]
@ehula new release just out, I will be able to see for this functionnality then https://github.com/hyprland-community/hyprland-autoname-workspaces/releases/tag/1.0.0

**Comment by cyrinux** [comment]
@ehula it's ready, I'm just waiting for a `hyprland-rs` to release, you will have a full class/title/initial class/initial title support. 🍒
