### ISSUE TITLE
[BUG] Immediate crash

### ISSUE THREAD

**Issue by Euro20179** [hyprland-community/hyprland-autoname-workspaces#58]
**Describe the bug**
As soon as I start the program, it crashes

**To Reproduce**
In versions 0.5.0+ it crashes immediately no matter what, in prior versions it only crashes if the .lock file in /tmp is present when trying to run.

**Expected behavior**
Doesn't crash

**Linux Distro (please complete the following information):**
 - Arch

**Program version?**
 - 0.5.4 (starts breaking in 0.5.0)

**Additional context**

Full trace back

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid type: string \"0x888346f0\", expected struct Client", line: 120, column: 30))', src/renamer/mod.rs:43:38
stack backtrace:
   0:     0x559efa83591a - <unknown>
   1:     0x559efa856c9e - <unknown>
   2:     0x559efa832c25 - <unknown>
   3:     0x559efa8356e5 - <unknown>
   4:     0x559efa836e9f - <unknown>
   5:     0x559efa836bdb - <unknown>
   6:     0x559efa837448 - <unknown>
   7:     0x559efa837349 - <unknown>
   8:     0x559efa835d86 - <unknown>
   9:     0x559efa837052 - <unknown>
  10:     0x559efa69c2f3 - <unknown>
  11:     0x559efa69c7a3 - <unknown>
  12:     0x559efa6fcf0a - <unknown>
  13:     0x559efa6edf33 - <unknown>
  14:     0x559efa6e8f29 - <unknown>
  15:     0x559efa82da5c - <unknown>
  16:     0x559efa6fdbd5 - <unknown>
  17:     0x7fad33658850 - <unknown>
  18:     0x7fad3365890a - __libc_start_main
  19:     0x559efa69c8e5 - <unknown>
  20:                0x0 - <unknown>
```

**Comment by cyrinux** [comment]
Hmm, can you share me your config file? Is it crashing too if all the config file is in comment?

**Comment by cyrinux** [comment]
Can you use also hyprland-git version if it is not the case?

**Comment by cyrinux** [comment]
```
...
        // Connect to Hyprland
        let binding = Clients::get().unwrap();
...
``` 

It crashes on the `hyprland-rs` call to get the clients list. So yeah, you have a too old hyprlland version 🤔

**Comment by Euro20179** [comment]
> It crashes on the hyprland-rs call to get the clients list. So yeah, you have a too old hyprlland version thinking

This was it, thanks!
