### ISSUE TITLE
support regex substitution

### ISSUE THREAD

**Issue by hotburger** [hyprland-community/hyprland-autoname-workspaces#69]
Titles can be very long. I would like to be able to use regex capture groups and substitution to shorten them.

For example:
foot with a title of: `emerge: (13 of 20) dev-lang/rust-1.69.0-r1 Compile:`
and with config:
```
[title."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "$1"
```
should display `(13 of 20) dev-lang/rust`

**Comment by cyrinux** [comment]
Hi, thanks for the idea. 
Interesting, I will study this after the new incoming release. 🍰

**Comment by hotburger** [comment]
Thanks for your work, I really appreciate it. The substitution works, but looking at the debug logs the title is only being updated when the window is focused. Is this a limitation of the IPC?

**Comment by cyrinux** [comment]
Ho, yes, I will this, we update on some event, but there is no "title change" event for the moment afaik. I will study this.

**Comment by cyrinux** [comment]
I can reproduce your test, I can't find an event in hyprland codebase for this for the moment, this will need to be first implement here.

**Comment by cyrinux** [comment]
I will be able to patch after those PR get validated and merged:

https://github.com/hyprland-community/hyprland-rs/pull/56
https://github.com/hyprwm/Hyprland/pull/2419
