### ISSUE TITLE
Custom Workspace Names

### ISSUE THREAD

**Issue by donovanglover** [hyprland-community/hyprland-autoname-workspaces#79]
**Is your feature request related to a problem? Please describe.**
I prefer using kanji for the workspace names over the usual numbers.

**Describe the solution you'd like**
It would be nice if there was a way to map workspace ids to text so any identifier can be used for workspaces. This would be similar to [waybar](https://github.com/Alexays/Waybar/wiki/Module:-Workspaces#example).

**Describe alternatives you've considered**
I tried using [named workspaces](https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces) in Hyprland (`name: 一`, etc.) but `hyprland-autoname-workspaces` only uses the id.

**Additional context**
`hyprland-autoname-workspaces` *could* add support for named workspaces so the name of the workspace is used instead of the id, however this would break scripts that identify the workspace by its name. Simply adding a new config option to [`src/renamer/mod.rs`](https://github.com/hyprland-community/hyprland-autoname-workspaces/blob/259fed002ece9de40863abe65d5e364d6e4f8477/src/renamer/mod.rs#L236-L253) seems like the best solution.

**Comment by cyrinux** [comment]
Thanks for the idea, I will try to implement this soon

**Comment by cyrinux** [comment]
@donovanglover the feature is add on the master branch, can you please try ?

**Comment by donovanglover** [comment]
@cyrinux It works great, thank you! If there's going to be another release soon, I can update https://github.com/NixOS/nixpkgs/pull/236515

**Comment by cyrinux** [comment]
Cool! I will do a release as soon as we can do a release of hyprland-rs. In theory I can cut a tag right now but I will no be able to publish the crate as I actually use the master branch of hyprland-rs.

**Comment by cyrinux** [comment]
@donovanglover if you have any idea about https://github.com/NixOS/nix/issues/8479 this can unlock the release then 🥹

**Comment by cyrinux** [comment]
@donovanglover I release the version `1.1.0`, if you can update nixos package 🙏🏻
