### ISSUE TITLE
Unknown icon on app closing remaining

### ISSUE THREAD

**Issue by cyrinux** [hyprland-community/hyprland-autoname-workspaces#86]
**Describe the bug**
since the last fix there is a new bug, when we close a client, we can saw on app closing the unknown icon remaining.

**To Reproduce**

1. Open a app
2. Close the app and see the unknown icon
3. Open another, or same app, or whatever action that trigger a refresh to see it disappear

**Expected behavior**
This icon shouldnt appear

**Comment by NTICompass** [comment]
I have what I think is the same issue.  I open a program that closes itself to the system tray.  Something like Slack or Discord.

Whenever I close the windows (and they close to the system tray), then I get a unknown app icon stuck on that workspace.

Examples:
Slack and Discord are open on workspace 2:
![05 07 2023_shot_12:19:18](https://github.com/hyprland-community/hyprland-autoname-workspaces/assets/409247/b327de3b-a7d7-41f6-b852-82c6ee22cffc)

I closed both of them and they are in the system tray.  And they are now "unknown" apps stuck forever on workspace 2.  The unknown icons go away if I re-open the Slack or Discord windows.
![05 07 2023_shot_12:19:26](https://github.com/hyprland-community/hyprland-autoname-workspaces/assets/409247/f523397e-b717-4a93-924d-7eb86b915ad4)

**Comment by NTICompass** [comment]
I think I "fixed" this issue with the following config:

```
[exclude]
"" = "^$"
```

**Comment by cyrinux** [comment]
My last commit fix this bug
