### ISSUE TITLE
Can't work for now since hyprland remove wlr workspace protocol support

### ISSUE THREAD

**Issue by cyrinux** [hyprland-community/hyprland-autoname-workspaces#98]
Waybar `wlr/workspaces` doesn't work anymore with last hyprland-git version since this commit
https://github.com/hyprwm/Hyprland/commit/bb0933437f4602080a66cc877fee36dce8dcb3ff

A new `hyprland/workspaces` in dev https://github.com/Alexays/Waybar/issues/2271 but it doesn't provide the same feature as autoname for to now.

To be study how make it work again 🆘

**Comment by mentalAdventurer** [comment]
Thank you for fixing this issue so fast :heart:

**Comment by cyrinux** [comment]
@maximbaz in the place 😘
